version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    cyclop:
      max-complexity: 10
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples/
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples/
